swagger: "2.0"
info:
  description: Rest API for HTML-PDF-Example
  version: "1.0.0"
  title: HTML-PDF-Example
servers:
- url: http://localhost:3000/
  description: Server
paths:
  /pdf:
    post:
      summary: Create pdf using templeate and your data
      description: Optional extended description in CommonMark or HTML.
      parameters:
      - in: body
        name: body
        schema:
          type: object
          properties:
            dealer:
              type: string
            certificate:
              type: string
            brandAdmin:
              type: string
            images:
              type: string
            copyTitle:
              type: string
            device:
              type: string
            ip:
              type: string
            user:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
            activationDate:
              type: string
            isPrivateClient:
              type: boolean
      responses:
            '200':    # status code
              description: A JSON array of user names
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      type: string